import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Educational content about CIBIL scores — shown after the financial wellness quiz.
class CibilScoreGuideScreen extends StatelessWidget {
  const CibilScoreGuideScreen({super.key});

  static const Color _navy = Color(0xFF1A2744);
  static const Color _text = Color(0xFF1A1A1A);
  static const Color _muted = Color(0xFF6B7280);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF5F7FA),
      body: CustomScrollView(
        slivers: [
          SliverAppBar(
            expandedHeight: 120,
            pinned: true,
            backgroundColor: _navy,
            foregroundColor: Colors.white,
            leading: IconButton(
              icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 20),
              onPressed: () => Navigator.pop(context),
            ),
            flexibleSpace: FlexibleSpaceBar(
              title: Text(
                'Understanding CIBIL',
                style: GoogleFonts.inter(
                  fontWeight: FontWeight.bold,
                  fontSize: 17,
                ),
              ),
              centerTitle: true,
              background: Container(
                decoration: const BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                    colors: [
                      Color(0xFF1A2744),
                      Color(0xFF243B5C),
                      Color(0xFF1E3250),
                    ],
                  ),
                ),
              ),
            ),
          ),
          SliverPadding(
            padding: const EdgeInsets.fromLTRB(20, 20, 20, 100),
            sliver: SliverList(
              delegate: SliverChildListDelegate([
                _emojiTitle(context, '📊', 'What is a CIBIL Score?'),
                _p(
                  'A CIBIL Score is a 3-digit number that shows how trustworthy you are with credit.',
                ),
                _p(
                  'It helps banks and lenders decide whether they should give you a loan or credit card.',
                ),
                _subheading('In India, the score ranges from:'),
                _highlightBox('300 to 900'),
                const SizedBox(height: 16),
                _subheading('Score categories:'),
                const SizedBox(height: 10),
                _scoreRow('🔴', '300 – 549', 'Very Poor', const Color(0xFFEF4444)),
                _scoreRow('🟠', '550 – 649', 'Poor', const Color(0xFFF97316)),
                _scoreRow('🟡', '650 – 699', 'Average', const Color(0xFFEAB308)),
                _scoreRow('🟢', '700 – 749', 'Good', const Color(0xFF22C55E)),
                _scoreRow('⭐', '750 – 900', 'Excellent', const Color(0xFF8B5CF6)),
                _p(
                  'The higher your score, the easier it is to get loans.',
                ),
                _p(
                  'CIBIL score is generated by the credit bureau TransUnion CIBIL based on your credit history.',
                ),
                const SizedBox(height: 24),
                _emojiTitle(context, '👍', 'Benefits of Having a Good CIBIL Score'),
                _p(
                  'If your CIBIL score is 750 or above, you get many financial advantages.',
                ),
                _bulletSection(
                  title: '🏦 Easy Loan Approval',
                  body:
                      'Banks trust people with high credit scores. Your loan approval chances increase significantly.',
                ),
                _bulletSection(
                  title: '💰 Lower Interest Rates',
                  body:
                      'People with good scores often get cheaper interest rates on home loans, car loans, and personal loans.',
                ),
                _subheading('Example:'),
                _exampleBox(
                  'Good score → 8–9% interest\nLow score → 12–15% interest',
                ),
                _p('This can save lakhs of rupees over time.'),
                _bulletSection(
                  title: '💳 Easy Credit Card Approval',
                  body:
                      'Banks easily approve credit cards when your score is good.',
                ),
                _bulletSection(
                  title: '🚀 Higher Credit Limit',
                  body:
                      'People with good credit scores receive higher credit card limits.',
                ),
                const SizedBox(height: 24),
                _emojiTitle(context, '⚠️', 'Problems Caused by a Low CIBIL Score'),
                _p(
                  'If your CIBIL score is low, you may face several financial problems.',
                ),
                _bulletSection(
                  title: '❌ Loan Rejection',
                  body:
                      'Banks may reject your loan application immediately.',
                ),
                _bulletSection(
                  title: '❌ High Interest Rates',
                  body:
                      'Even if the loan is approved, you may have to pay very high interest.',
                ),
                _bulletSection(
                  title: '❌ Difficulty Getting Credit Cards',
                  body: 'Banks may refuse to issue credit cards.',
                ),
                _bulletSection(
                  title: '❌ Low Credit Limit',
                  body:
                      'If approved, you might get a very small credit limit.',
                ),
                const SizedBox(height: 24),
                _emojiTitle(context, '📈', 'How to Improve Your CIBIL Score'),
                _p(
                  'If your score is low, don’t worry. You can improve it by following these steps.',
                ),
                _bulletSection(
                  title: '⏰ Pay EMIs and Credit Card Bills on Time',
                  body:
                      'Late payments are the biggest reason for a bad credit score.\n\nAlways pay:\n✔ Loan EMIs\n✔ Credit card bills\n\nOn-time payments gradually increase your score.',
                ),
                _bulletSection(
                  title: '💳 Keep Credit Card Usage Low',
                  body:
                      'Experts recommend using less than 30% of your credit limit.',
                ),
                _subheading('Example:'),
                _exampleBox(
                  'Credit limit → ₹1,00,000\nBest usage → ₹30,000 or less',
                ),
                _p('High usage can reduce your score.'),
                _bulletSection(
                  title: '📉 Avoid Applying for Too Many Loans',
                  body:
                      'Applying for many loans in a short time can reduce your score because banks see you as credit hungry.',
                ),
                _bulletSection(
                  title: '📅 Maintain Old Credit Accounts',
                  body:
                      'Older credit history improves your credit score. Avoid closing your oldest credit card.',
                ),
                const SizedBox(height: 24),
                _emojiTitle(context, '🧠', 'Smart Credit Habits Everyone Should Follow'),
                _p(
                  'To maintain a strong CIBIL score, follow these habits.',
                ),
                _checkList(const [
                  'Pay bills before due date',
                  'Use credit cards responsibly',
                  'Avoid unnecessary loans',
                  'Monitor your credit report regularly',
                  'Maintain a healthy credit mix',
                ]),
                _p(
                  'These habits help keep your credit score above 750.',
                ),
                const SizedBox(height: 24),
                _emojiTitle(context, '🚨', 'Common Mistakes That Damage CIBIL Score'),
                _p(
                  'Many people unknowingly damage their credit score by doing these mistakes.',
                ),
                _checkList(const [
                  'Missing EMI payments',
                  'Paying only minimum credit card dues',
                  'Taking too many personal loans',
                  'Settling loans instead of fully paying them',
                  'Using almost 100% credit limit',
                ], bullet: '❌'),
                _p('Avoiding these mistakes can protect your credit score.'),
              ]),
            ),
          ),
        ],
      ),
      bottomNavigationBar: SafeArea(
        child: Padding(
          padding: const EdgeInsets.fromLTRB(20, 8, 20, 16),
          child: _PillCtaButton(
            label: 'Continue to Home',
            onPressed: () => Navigator.of(context).pop(),
          ),
        ),
      ),
    );
  }

  Widget _emojiTitle(BuildContext context, String emoji, String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12, top: 4),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(emoji, style: const TextStyle(fontSize: 22)),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              title,
              style: GoogleFonts.inter(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: _text,
                height: 1.3,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _p(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Text(
        text,
        style: GoogleFonts.inter(
          fontSize: 15,
          height: 1.55,
          color: _text,
        ),
      ),
    );
  }

  Widget _subheading(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8, top: 4),
      child: Text(
        text,
        style: GoogleFonts.inter(
          fontSize: 15,
          fontWeight: FontWeight.w700,
          color: _text,
        ),
      ),
    );
  }

  Widget _highlightBox(String text) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE5E7EB)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Text(
        text,
        textAlign: TextAlign.center,
        style: GoogleFonts.inter(
          fontSize: 18,
          fontWeight: FontWeight.bold,
          color: _navy,
        ),
      ),
    );
  }

  Widget _scoreRow(String emoji, String range, String label, Color accent) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: const Color(0xFFE5E7EB)),
        ),
        child: Row(
          children: [
            Text(emoji, style: const TextStyle(fontSize: 18)),
            const SizedBox(width: 10),
            Expanded(
              child: Text(
                '$range → $label',
                style: GoogleFonts.inter(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: _text,
                ),
              ),
            ),
            Container(
              width: 8,
              height: 28,
              decoration: BoxDecoration(
                color: accent,
                borderRadius: BorderRadius.circular(4),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _bulletSection({required String title, required String body}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: GoogleFonts.inter(
              fontSize: 16,
              fontWeight: FontWeight.w700,
              color: _text,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            body,
            style: GoogleFonts.inter(
              fontSize: 15,
              height: 1.55,
              color: _muted,
            ),
          ),
        ],
      ),
    );
  }

  Widget _exampleBox(String text) {
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFFEFF6FF),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFBFDBFE)),
      ),
      child: Text(
        text,
        style: GoogleFonts.inter(
          fontSize: 14,
          height: 1.5,
          color: const Color(0xFF1E40AF),
          fontWeight: FontWeight.w500,
        ),
      ),
    );
  }

  Widget _checkList(List<String> items, {String bullet = '✔'}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: items.map((e) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 8),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(bullet, style: const TextStyle(fontSize: 14)),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  e,
                  style: GoogleFonts.inter(
                    fontSize: 15,
                    height: 1.45,
                    color: _text,
                  ),
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }
}

class _PillCtaButton extends StatelessWidget {
  const _PillCtaButton({
    required this.label,
    required this.onPressed,
  });

  final String label;
  final VoidCallback onPressed;

  static const Color _navy = Color(0xFF1A2744);

  @override
  Widget build(BuildContext context) {
    return Material(
      color: _navy,
      elevation: 4,
      shadowColor: Colors.black.withValues(alpha: 0.32),
      borderRadius: BorderRadius.circular(28),
      child: InkWell(
        onTap: onPressed,
        borderRadius: BorderRadius.circular(28),
        splashColor: Colors.white.withValues(alpha: 0.12),
        child: SizedBox(
          height: 52,
          width: double.infinity,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Flexible(
                  child: Text(
                    label,
                    textAlign: TextAlign.center,
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                    style: GoogleFonts.inter(
                      fontSize: 15,
                      fontWeight: FontWeight.w700,
                      color: Colors.white,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                const Icon(
                  Icons.arrow_forward_rounded,
                  color: Colors.white,
                  size: 20,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
